#pos(ex1@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). ghost(east, 9). food(west, 5). food(west, 10). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 7). ghost(east, 6). food(east, 8). food(east, 6). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 7). capsule(east, 9). capsule(east, 4).}).
#pos(ex2@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 6). capsule(east, 10). food(east, 8). capsule(east, 5). ghost(west, 9.0). food(east, 7). ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 2). food(west, 7).}).
#pos(ex3@0, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). food(west, 8). food(east, 9). food(west, 4). food(east, 8). ghost(west, 7.0). ghost(east, 6.0). food(west, 3). wall(east). wall(north). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6).}).
#pos(ex4@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). food(west, 5). food(east, 10). food(north, 1). ghost(west, 5.0). capsule(east, 7). capsule(west, 4). food(west, 6).}).
#pos(ex5@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). wall(north). ghost(west, 3.0). food(west, 3). capsule(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 8). food(west, 5). food(east, 10). food(west, 6).}).
#pos(ex6@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 6.0). food(west, 4). capsule(north, 2). food(east, 3). wall(north). food(west, 3). wall(east). wall(south). wall(west). food(west, 2). food(west, 1). food(west, 5). capsule(east, 9). ghost(west, 1.0).}).
#pos(ex7@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). wall(north). capsule(west, 3). food(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). capsule(east, 8). food(west, 5). food(east, 10). ghost(east, 4.0). food(west, 6). ghost(west, 1.0).}).
#pos(ex8@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). ghost(north, 2.0). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(north, 1). capsule(east, 7). capsule(west, 4). food(west, 6). ghost(west, 1.0).}).
#pos(ex9@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). food(west, 8). food(east, 9). food(east, 8). food(west, 4). wall(north). wall(east). ghost(west, 2.0). wall(west). wall(south). food(west, 2). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6). ghost(west, 1.0).}).
#pos(ex10@1, {move(north)}, {move(south), move(east), move(west)}, {food(west, 8). food(east, 9). food(east, 8). wall(north). food(west, 3). food(west, 9). ghost(west, 2.0). wall(east). ghost(west, 1.0). ghost(east, 9.0). wall(west). wall(south). food(west, 5). capsule(east, 5). capsule(east, 10). food(east, 10). capsule(west, 6). food(west, 7). food(west, 6). food(east, 7).}).
#pos(ex11@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). food(west, 8). food(east, 9). food(east, 8). ghost(south, 1.0). capsule(east, 9). wall(north). wall(east). ghost(west, 2.0). wall(west). wall(south). food(west, 2). ghost(east, 7.0). food(east, 10). food(west, 7). food(west, 6). capsule(east, 4). food(east, 7).}).
#pos(ex12@1, {move(north)}, {move(south), move(east), move(west)}, {food(west, 8). food(east, 9). food(east, 8). wall(north). food(west, 3). food(west, 9). ghost(west, 2.0). wall(east). ghost(west, 1.0). wall(west). food(east, 10). wall(south). capsule(east, 8). food(east, 6). capsule(west, 6). food(west, 7). ghost(east, 5.0). capsule(east, 3). food(east, 7).}).
#pos(ex13@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). capsule(east, 2). food(west, 8). food(east, 9). food(west, 4). food(east, 8). wall(north). wall(east). food(west, 9). ghost(west, 2.0). ghost(west, 1.0). wall(west). wall(south). food(east, 10). food(west, 7). ghost(east, 5.0). capsule(east, 7). food(east, 6). food(east, 7).}).
#pos(ex14@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 8). food(east, 9). food(east, 8). wall(north). wall(east). food(west, 9). ghost(west, 2.0). ghost(west, 1.0). capsule(east, 1). wall(west). food(east, 5). food(east, 10). wall(south). capsule(east, 6). food(west, 5). food(west, 10). capsule(west, 6). ghost(east, 5.0). food(east, 6). food(east, 7).}).
#pos(ex15@1, {move(west)}, {move(south), move(north), move(east)}, {food(east, 9). food(east, 8). wall(north). ghost(east, 3.5). food(west, 10). wall(east). food(west, 9). ghost(west, 3.5). wall(west). food(east, 5). wall(south). ghost(west, 1.5). capsule(east, 5). capsule(west, 7). food(east, 6). food(west, 6). food(east, 4). food(east, 7).}).
#pos(ex16@3, {move(west)}, {move(south), move(north), move(east)}, {food(west, 8). food(east, 9). food(east, 8). wall(north). ghost(west, 3.0). wall(east). food(west, 9). wall(west). food(east, 5). food(east, 10). wall(south). capsule(east, 6). food(west, 5). food(west, 10). capsule(west, 6). ghost(east, 4.0). ghost(west, 9.0). food(east, 6). food(east, 7).}).
#pos(ex17@3, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). food(west, 8). food(east, 9). food(west, 4). food(east, 8). ghost(west, 7.0). ghost(east, 4.5). wall(east). food(west, 9). ghost(east, 2.5). wall(north). wall(west). wall(south). food(east, 10). food(west, 7). capsule(east, 7). food(east, 6). food(east, 7).}).
#pos(ex18@3, {move(south)}, {move(north), move(east), move(west)}, {food(west, 8). food(east, 9). food(east, 8). ghost(west, 7.0). ghost(east, 5.0). wall(north). food(west, 3). wall(east). wall(west). wall(south). capsule(east, 8). food(east, 10). food(west, 7). ghost(east, 4.0). capsule(west, 4). food(west, 6). food(east, 7).}).
#pos(ex19@3, {move(south)}, {move(north), move(east), move(west)}, {capsule(west, 5). food(west, 8). food(east, 9). food(east, 8). ghost(west, 7.0). ghost(east, 3.5). capsule(east, 9). wall(east). wall(north). wall(west). wall(south). food(west, 2). food(east, 10). food(west, 7). food(west, 6). food(east, 7).}).
#pos(ex20@3, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 3.0). food(west, 8). food(east, 9). food(east, 8). wall(north). food(west, 3). food(west, 9). wall(east). ghost(east, 2.0). wall(west). wall(south). food(west, 5). capsule(east, 10). food(east, 10). capsule(west, 6). food(west, 7). ghost(west, 5.0). food(west, 6). food(east, 7).}).
#pos(ex21@3, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). food(west, 8). food(east, 9). food(east, 8). food(west, 4). ghost(east, 4.5). ghost(west, 3.0). wall(east). wall(north). ghost(east, 2.5). wall(west). wall(south). food(west, 2). food(west, 5). food(east, 10). food(west, 7). food(west, 6).}).
#pos(ex22@3, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(north, 1). capsule(west, 4). food(west, 6). ghost(west, 1.0).}).
#pos(ex23@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). ghost(east, 9). food(west, 5). food(west, 10). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 7). ghost(east, 6). food(east, 8). food(east, 6). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 7). capsule(east, 9). capsule(east, 4).}).
#pos(ex24@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 6). capsule(east, 10). food(east, 8). capsule(east, 5). ghost(west, 9.0). food(east, 7). ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 2). food(west, 7).}).
#pos(ex25@0, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). food(west, 8). food(east, 9). food(west, 4). food(east, 8). ghost(west, 7.0). ghost(east, 6.0). food(west, 3). wall(east). wall(north). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6).}).
#pos(ex26@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). food(west, 5). food(east, 10). food(north, 1). ghost(west, 5.0). capsule(east, 7). capsule(west, 4). food(west, 6).}).
#pos(ex27@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). wall(north). capsule(west, 3). food(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 8). food(west, 5). food(east, 10). ghost(east, 5.0). food(west, 6).}).
#pos(ex28@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). capsule(north, 2). food(east, 3). wall(north). food(west, 3). wall(east). wall(south). wall(west). food(west, 2). food(west, 1). food(west, 5). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex29@1, {move(west)}, {move(south), move(north), move(east)}, {food(north, 4). ghost(east, 6.0). food(west, 4). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 10). ghost(east, 5.0). capsule(east, 3). food(east, 4).}).
#pos(ex30@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 6.0). wall(north). wall(east). wall(west). food(east, 5). wall(south). food(north, 3). food(north, 2). food(north, 1). ghost(east, 5.0). capsule(east, 4).}).
#pos(ex31@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 4.0). wall(north). wall(east). wall(west). wall(south). capsule(east, 10). food(north, 2). food(north, 1). ghost(east, 5.0). capsule(east, 3). food(east, 4).}).
#pos(ex32@1, {move(north)}, {move(south), move(east), move(west)}, {capsule(east, 2). ghost(east, 6.0). wall(north). food(east, 3). wall(east). wall(west). food(east, 5). wall(south). food(north, 1). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex33@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 6.0). wall(north). wall(east). food(east, 2). wall(west). wall(south). food(east, 6). ghost(east, 5.0). capsule(east, 3). capsule(east, 10).}).
#pos(ex34@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 6.0). wall(north). wall(east). food(east, 1). wall(west). wall(south). ghost(east, 5.0). capsule(east, 4). food(east, 7).}).
#pos(ex35@1, {move(east)}, {move(south), move(north), move(west)}, {wall(north). wall(east). wall(west). wall(south). capsule(east, 10). food(east, 6). ghost(west, 5.0). capsule(east, 3). ghost(south, 4.0).}).
#pos(ex36@1, {move(east)}, {move(south), move(north), move(west)}, {wall(north). wall(east). ghost(west, 6.0). capsule(south, 2). wall(south). food(east, 5). wall(west). ghost(west, 5.0). capsule(east, 9).}).
#pos(ex37@1, {move(east)}, {move(south), move(north), move(west)}, {wall(north). capsule(west, 3). wall(east). ghost(west, 6.0). wall(west). wall(south). capsule(east, 8). food(east, 10). ghost(west, 5.0). food(east, 4).}).
#pos(ex38@1, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). food(south, 3). wall(north). wall(east). ghost(west, 6.0). ghost(east, 9.0). wall(west). wall(south). food(east, 10). ghost(west, 5.0). capsule(east, 7). capsule(west, 4).}).
#pos(ex39@1, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 4.0). food(east, 9). wall(north). capsule(west, 3). wall(east). food(south, 2). wall(west). wall(south). ghost(east, 7.0). capsule(east, 6). food(east, 10). ghost(west, 5.0).}).
#pos(ex40@1, {move(south)}, {move(north), move(east), move(west)}, {ghost(east, 5.0). food(east, 9). wall(north). wall(east). ghost(west, 6.0). wall(west). wall(south). food(south, 1). capsule(east, 5). capsule(west, 2). food(east, 10). ghost(west, 5.0). capsule(east, 10).}).
#pos(ex41@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). food(east, 9). wall(north). capsule(west, 3). wall(east). ghost(west, 6.0). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(west, 5.0).}).
#pos(ex42@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). ghost(west, 4.0). food(east, 9). wall(north). ghost(west, 3.0). wall(east). wall(west). wall(south). capsule(east, 5). capsule(west, 2). food(east, 10). capsule(east, 10).}).
#pos(ex43@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). food(east, 9). wall(north). ghost(west, 3.0). capsule(west, 3). wall(east). ghost(west, 2.0). wall(west). wall(south). capsule(east, 6). food(east, 10).}).
#pos(ex44@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). food(east, 9). wall(north). ghost(west, 3.0). wall(east). wall(west). wall(south). food(east, 10). ghost(east, 5.0). capsule(east, 7). capsule(west, 4).}).
#pos(ex45@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). ghost(west, 4.0). food(east, 9). food(east, 8). wall(north). ghost(west, 3.0). wall(east). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(east, 5.0).}).
#pos(ex46@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). ghost(west, 4.0). wall(north). ghost(west, 3.0). wall(east). wall(west). wall(south). ghost(south, 3.0). capsule(east, 5). capsule(east, 10). food(east, 10). capsule(west, 6). food(east, 7).}).
#pos(ex47@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). ghost(west, 4.0). wall(north). ghost(west, 3.0). wall(east). wall(west). food(east, 10). wall(south). capsule(west, 7). food(east, 6). capsule(east, 9). capsule(east, 4). food(east, 7).}).
#pos(ex48@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). ghost(west, 4.0). wall(north). ghost(west, 3.0). wall(east). capsule(west, 8). wall(west). food(east, 10). food(east, 5). wall(south). capsule(east, 8). food(east, 6). capsule(east, 3). food(east, 7).}).
#pos(ex49@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). ghost(west, 4.0). wall(north). ghost(west, 3.0). capsule(west, 9). wall(east). capsule(south, 2). wall(west). food(east, 5). wall(south). food(east, 10). food(east, 4). capsule(east, 7). food(east, 6). food(east, 7).}).
#pos(ex50@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). ghost(west, 4.0). food(east, 3). ghost(west, 3.0). capsule(west, 3). capsule(west, 10). wall(east). wall(north). wall(west). food(east, 5). wall(south). capsule(east, 6). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex51@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). food(east, 8). wall(north). food(east, 3). ghost(west, 3.0). wall(east). food(east, 2). wall(west). food(east, 5). wall(south). capsule(east, 5). food(east, 6). ghost(west, 5.0). capsule(west, 4). food(east, 4). food(east, 7).}).
#pos(ex52@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). ghost(west, 4.0). ghost(west, 7.0). wall(north). food(east, 3). ghost(west, 3.0). wall(east). food(east, 2). food(east, 1). wall(west). food(east, 5). wall(south). capsule(east, 4). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex53@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). food(south, 3). food(east, 3). ghost(west, 3.0). wall(east). capsule(east, 3). food(south, 2). wall(north). food(east, 2). wall(west). food(east, 5). food(south, 1). wall(south). food(east, 6). capsule(west, 6). food(south, 4). ghost(west, 9.0). food(east, 1). food(east, 4).}).
#pos(ex54@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). food(west, 4). food(south, 3). food(east, 3). ghost(west, 3.0). food(west, 3). wall(east). wall(north). food(east, 2). capsule(south, 2). wall(west). food(east, 5). food(west, 2). wall(south). food(west, 5). capsule(west, 7). food(south, 4). food(east, 1). food(east, 4).}).
#pos(ex55@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). food(west, 4). wall(north). food(east, 3). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). food(east, 2). wall(west). wall(south). food(west, 5). ghost(west, 5.0). food(west, 6). food(east, 1). food(east, 4).}).
#pos(ex56@2, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). food(south, 3). ghost(west, 7.0). capsule(west, 9). wall(east). wall(north). food(south, 2). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). food(west, 7). capsule(west, 4). food(west, 6).}).
#pos(ex57@2, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). ghost(west, 7.0). wall(north). capsule(west, 3). food(west, 3). capsule(west, 8). food(south, 2). wall(east). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). ghost(west, 9.0). food(west, 6).}).
#pos(ex58@2, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). ghost(west, 7.0). wall(north). food(west, 3). wall(east). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). capsule(west, 7). capsule(west, 2).}).
#pos(ex59@2, {move(north)}, {move(south), move(east), move(west)}, {ghost(west, 7.0). food(west, 4). wall(north). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 2). food(west, 5). ghost(west, 9.0).}).
#pos(ex60@2, {move(north)}, {move(south), move(east), move(west)}, {food(west, 4). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 5). ghost(west, 8.0). capsule(west, 7). capsule(west, 2). ghost(west, 9.0).}).
#pos(ex61@2, {move(north)}, {move(south), move(east), move(west)}, {food(west, 4). wall(north). ghost(west, 10.0). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). wall(west). wall(south). food(west, 5). food(west, 6).}).
#pos(ex62@2, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). wall(north). capsule(west, 9). wall(east). wall(west). wall(south). food(west, 5). food(west, 7). capsule(west, 4). food(west, 6).}).
#pos(ex63@2, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). wall(north). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). wall(west). wall(south). food(west, 5). food(west, 6).}).
#pos(ex64@2, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). food(south, 3). ghost(west, 10.0). wall(north). food(west, 3). wall(east). capsule(south, 2). wall(west). wall(south). food(west, 2). food(west, 5). capsule(west, 7). food(south, 4). ghost(west, 9.0).}).
#pos(ex65@2, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 7.0). food(south, 3). wall(north). wall(east). capsule(east, 3). food(south, 2). wall(west). food(east, 5). food(south, 1). wall(south). ghost(west, 8.0). capsule(west, 6). food(south, 4). ghost(west, 9.0). food(east, 4).}).
#pos(ex66@2, {move(south)}, {move(north), move(east), move(west)}, {capsule(west, 5). capsule(east, 2). food(south, 3). food(east, 3). wall(north). wall(east). food(south, 2). wall(west). wall(south). food(south, 1). ghost(west, 8.0). ghost(west, 5.0). ghost(west, 9.0). food(east, 4).}).
#pos(ex67@2, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 7.0). wall(north). food(east, 3). ghost(west, 3.0). wall(east). food(south, 2). food(east, 2). capsule(east, 1). wall(west). wall(south). food(south, 1). ghost(west, 8.0). capsule(west, 4).}).
#pos(ex68@2, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). capsule(east, 2). ghost(west, 7.0). wall(north). ghost(west, 3.0). wall(east). ghost(west, 6.0). food(east, 2). wall(west). wall(south). food(south, 1). food(east, 1).}).
#pos(ex69@2, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 7.0). wall(north). wall(east). wall(west). wall(south). food(west, 2). food(south, 1). ghost(west, 8.0). capsule(west, 6). ghost(west, 5.0). capsule(north, 1).}).
#pos(ex70@2, {move(west)}, {move(south), move(north), move(east)}, {ghost(west, 4.0). ghost(west, 7.0). capsule(north, 2). wall(north). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 1). capsule(west, 7).}).
#pos(ex71@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). ghost(east, 9). food(west, 5). food(west, 10). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 7). ghost(east, 6). food(east, 8). food(east, 6). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 7). capsule(east, 9). capsule(east, 4).}).
#pos(ex72@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 6). capsule(east, 10). food(east, 8). capsule(east, 5). ghost(west, 9.0). food(east, 7). ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 2). food(west, 7).}).
#pos(ex73@0, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). food(west, 8). food(east, 9). food(west, 4). food(east, 8). ghost(west, 7.0). ghost(east, 6.0). food(west, 3). wall(east). wall(north). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6).}).
#pos(ex74@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). food(west, 5). food(east, 10). food(north, 1). ghost(west, 5.0). capsule(east, 7). capsule(west, 4). food(west, 6).}).
#pos(ex75@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). wall(north). capsule(west, 3). food(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 8). food(west, 5). food(east, 10). ghost(east, 5.0). food(west, 6).}).
#pos(ex76@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). capsule(north, 2). food(east, 3). wall(north). food(west, 3). wall(east). wall(south). wall(west). food(west, 2). food(west, 1). food(west, 5). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex77@1, {move(west)}, {move(south), move(north), move(east)}, {food(north, 4). ghost(east, 6.0). food(west, 4). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 10). ghost(east, 5.0). capsule(east, 3). food(east, 4).}).
#pos(ex78@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 6.0). wall(north). wall(east). wall(west). food(east, 5). wall(south). food(north, 3). food(north, 2). food(north, 1). ghost(east, 5.0). capsule(east, 4).}).
#pos(ex79@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 4.0). wall(north). wall(east). wall(west). wall(south). capsule(east, 10). food(north, 2). food(north, 1). ghost(east, 5.0). capsule(east, 3). food(east, 4).}).
#pos(ex80@1, {move(north)}, {move(south), move(east), move(west)}, {capsule(east, 2). ghost(east, 6.0). wall(north). food(east, 3). wall(east). wall(west). food(east, 5). wall(south). ghost(east, 7.0). food(north, 1). capsule(east, 9).}).
#pos(ex81@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 6.0). wall(north). wall(east). food(east, 2). ghost(east, 9.0). wall(west). wall(south). food(east, 6). capsule(east, 3). capsule(east, 10).}).
#pos(ex82@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 6.0). wall(north). wall(east). food(east, 1). ghost(east, 9.0). wall(west). wall(south). capsule(east, 4). food(east, 7).}).
#pos(ex83@1, {move(east)}, {move(south), move(north), move(west)}, {wall(north). wall(east). wall(west). wall(south). ghost(east, 7.0). capsule(east, 10). food(east, 6). capsule(east, 3). ghost(south, 4.0).}).
#pos(ex84@1, {move(east)}, {move(south), move(north), move(west)}, {wall(north). wall(east). ghost(west, 6.0). capsule(south, 2). wall(south). food(east, 5). wall(west). ghost(east, 7.0). capsule(east, 9).}).
#pos(ex85@1, {move(east)}, {move(south), move(north), move(west)}, {wall(north). capsule(west, 3). wall(east). ghost(west, 6.0). wall(west). wall(south). ghost(east, 7.0). capsule(east, 8). food(east, 10). food(east, 4).}).
#pos(ex86@1, {move(south)}, {move(north), move(east), move(west)}, {ghost(east, 4.0). food(east, 9). ghost(east, 8.0). food(south, 3). wall(north). wall(east). wall(west). wall(south). food(east, 10). ghost(west, 5.0). capsule(east, 7). capsule(west, 4).}).
#pos(ex87@1, {move(south)}, {move(north), move(east), move(west)}, {ghost(east, 6.0). food(east, 9). ghost(west, 5.0). wall(north). capsule(west, 3). wall(east). food(south, 2). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(east, 4.0).}).
#pos(ex88@1, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). ghost(west, 5.0). wall(north). wall(east). wall(west). wall(south). food(south, 1). capsule(east, 5). capsule(west, 2). food(east, 10). ghost(east, 4.0). capsule(east, 10).}).
#pos(ex89@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 6.0). food(east, 9). wall(north). capsule(west, 3). wall(east). ghost(east, 2.0). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(west, 5.0).}).
#pos(ex90@1, {move(north)}, {move(south), move(east), move(west)}, {food(east, 9). wall(north). ghost(west, 3.0). wall(east). ghost(east, 2.0). wall(west). wall(south). capsule(east, 5). capsule(west, 2). food(east, 10). ghost(east, 4.0). capsule(east, 10).}).
#pos(ex91@1, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). wall(north). capsule(west, 3). wall(east). ghost(north, 1.0). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(east, 4.0).}).
#pos(ex92@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). food(east, 9). wall(north). wall(east). ghost(east, 2.0). wall(west). wall(south). capsule(east, 5). capsule(west, 2). food(east, 10). ghost(east, 4.0). capsule(east, 10).}).
#pos(ex93@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). ghost(east, 6.0). food(east, 9). wall(north). capsule(west, 3). wall(east). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(east, 4.0).}).
#pos(ex94@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). ghost(east, 6.0). food(east, 9). wall(north). wall(east). wall(west). wall(south). food(east, 10). capsule(east, 7). capsule(west, 4).}).
#pos(ex95@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). ghost(east, 3.0). food(east, 9). food(east, 8). wall(north). wall(east). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(east, 4.0). ghost(south, 4.0).}).
#pos(ex96@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). food(east, 9). food(east, 8). wall(north). ghost(south, 2.0). wall(east). ghost(west, 6.0). wall(west). wall(south). capsule(east, 5). capsule(east, 10). food(east, 10). capsule(west, 6). food(east, 7).}).
#pos(ex97@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). food(east, 9). food(east, 8). ghost(west, 4.0). wall(north). wall(east). ghost(west, 6.0). wall(west). food(east, 10). wall(south). capsule(west, 7). food(east, 6). capsule(east, 9). capsule(east, 4). food(east, 7).}).
#pos(ex98@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). food(east, 9). food(east, 8). ghost(west, 4.0). wall(north). wall(east). capsule(west, 8). ghost(west, 6.0). wall(west). food(east, 10). food(east, 5). wall(south). capsule(east, 8). food(east, 6). capsule(east, 3). food(east, 7).}).
#pos(ex99@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). food(east, 9). food(east, 8). ghost(west, 4.0). wall(north). capsule(west, 9). wall(east). ghost(west, 6.0). capsule(south, 2). wall(west). food(east, 5). wall(south). food(east, 10). food(east, 4). capsule(east, 7). food(east, 6). food(east, 7).}).
#pos(ex100@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). food(east, 9). food(east, 8). ghost(west, 4.0). food(east, 3). capsule(west, 3). wall(east). capsule(west, 10). wall(north). ghost(west, 6.0). wall(west). food(east, 5). wall(south). capsule(east, 6). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex101@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). food(east, 8). wall(north). food(east, 3). wall(east). food(east, 2). ghost(west, 6.0). wall(west). food(east, 5). wall(south). ghost(south, 3.0). capsule(east, 5). food(east, 6). capsule(west, 4). food(east, 4). food(east, 7).}).
#pos(ex102@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). wall(north). food(east, 3). wall(east). food(east, 2). food(east, 1). ghost(west, 6.0). food(east, 5). wall(west). wall(south). capsule(east, 4). food(east, 6). ghost(west, 5.0). food(east, 4). food(east, 7).}).
#pos(ex103@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 7.0). food(south, 3). food(east, 3). wall(north). wall(east). capsule(east, 3). food(south, 2). food(east, 2). ghost(west, 6.0). wall(west). food(east, 5). food(south, 1). wall(south). ghost(west, 8.0). food(east, 6). capsule(west, 6). food(south, 4). food(east, 1). food(east, 4).}).
#pos(ex104@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). food(south, 3). food(east, 3). ghost(west, 10.0). food(west, 3). wall(east). wall(north). food(east, 2). ghost(west, 6.0). capsule(south, 2). food(east, 5). food(west, 2). wall(west). wall(south). food(west, 5). capsule(west, 7). food(south, 4). ghost(west, 9.0). food(east, 1). food(east, 4).}).
#pos(ex105@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). wall(north). food(east, 3). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). food(east, 2). ghost(west, 6.0). wall(west). wall(south). food(west, 5). food(west, 6). food(east, 1). food(east, 4).}).
#pos(ex106@2, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). food(south, 3). wall(north). capsule(west, 9). wall(east). food(south, 2). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). food(west, 7). capsule(west, 4). food(west, 6).}).
#pos(ex107@2, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). wall(north). ghost(west, 10.0). capsule(west, 3). food(west, 3). capsule(west, 8). food(south, 2). wall(east). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). food(west, 6).}).
#pos(ex108@2, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). wall(north). food(west, 3). wall(east). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). ghost(west, 8.0). capsule(west, 7). capsule(west, 2). ghost(west, 9.0).}).
#pos(ex109@2, {move(north)}, {move(south), move(east), move(west)}, {food(west, 4). wall(north). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 2). food(west, 5). ghost(west, 8.0). ghost(west, 9.0).}).
#pos(ex110@2, {move(north)}, {move(south), move(east), move(west)}, {ghost(west, 7.0). food(west, 4). wall(north). food(west, 3). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 5). ghost(west, 8.0). capsule(west, 7). capsule(west, 2).}).
#pos(ex111@2, {move(north)}, {move(south), move(east), move(west)}, {food(west, 4). wall(north). ghost(west, 10.0). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). wall(west). wall(south). food(west, 5). ghost(west, 8.0). ghost(west, 9.0). food(west, 6).}).
#pos(ex112@2, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). wall(north). ghost(west, 10.0). capsule(west, 9). wall(east). wall(west). wall(south). food(west, 5). food(west, 7). capsule(west, 4). food(west, 6).}).
#pos(ex113@2, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). wall(north). ghost(west, 10.0). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). wall(west). wall(south). food(west, 5). food(west, 6).}).
#pos(ex114@2, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). food(south, 3). ghost(west, 10.0). wall(north). food(west, 3). wall(east). capsule(south, 2). wall(west). wall(south). food(west, 2). food(west, 5). capsule(west, 7). food(south, 4).}).
#pos(ex115@2, {move(south)}, {move(north), move(east), move(west)}, {food(south, 3). ghost(west, 10.0). wall(north). wall(east). capsule(east, 3). food(south, 2). wall(west). food(east, 5). food(south, 1). wall(south). ghost(west, 8.0). capsule(west, 6). food(south, 4). ghost(west, 9.0). food(east, 4).}).
#pos(ex116@2, {move(south)}, {move(north), move(east), move(west)}, {capsule(west, 5). capsule(east, 2). ghost(west, 7.0). food(south, 3). food(east, 3). wall(north). wall(east). food(south, 2). ghost(west, 6.0). wall(west). wall(south). food(south, 1). ghost(west, 8.0). food(east, 4).}).
#pos(ex117@2, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 4.0). wall(north). food(east, 3). wall(east). food(south, 2). ghost(west, 6.0). food(east, 2). capsule(east, 1). wall(west). food(south, 1). wall(south). ghost(west, 5.0). capsule(west, 4).}).
#pos(ex118@2, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). capsule(east, 2). wall(north). ghost(west, 3.0). wall(east). ghost(west, 6.0). food(east, 2). wall(west). wall(south). food(south, 1). food(east, 1).}).
#pos(ex119@2, {move(south)}, {move(north), move(east), move(west)}, {wall(north). ghost(west, 3.0). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 2). food(south, 1). ghost(west, 8.0). capsule(west, 6). capsule(north, 1).}).
#pos(ex120@2, {move(west)}, {move(south), move(north), move(east)}, {capsule(north, 2). wall(north). wall(east). wall(west). wall(south). food(west, 1). ghost(west, 8.0). capsule(west, 7). ghost(west, 5.0).}).
ranges_dist(0..10).
dir(north).
dir(south).
dir(east).
dir(west).


dist_thr(0).
dist_thr(1).
dist_thr(2).
dist_thr(4).


food_dist_geq(D, D1, D2) :- food(D, D1), dist_thr(D2), D1 >= D2.
food_dist_leq(D, D1, D2) :- food(D, D1), dist_thr(D2), D1 <= D2.
ghost_dist_geq(D, D1, D2) :- ghost(D, D1), dist_thr(D2), D1 >= D2.
ghost_dist_leq(D, D1, D2) :- ghost(D, D1), dist_thr(D2), D1 <= D2.
caps_dist_geq(D, D1, D2) :- capsule(D, D1), dist_thr(D2), D1 >= D2.
caps_dist_leq(D, D1, D2) :- capsule(D, D1), dist_thr(D2), D1 <= D2.

#modeb(1,food_dist_geq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,food_dist_leq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,ghost_dist_geq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,ghost_dist_leq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,caps_dist_geq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,caps_dist_leq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(not wall(var(dir))).

#modeh(move(var(dir))).

#maxv(3).

%bias declarations to ensure direction variables are the same
#bias(":- in_head(move(V0)), in_body(wall(X)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(food_dist_geq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(food_dist_leq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(ghost_dist_leq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(ghost_dist_geq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(caps_dist_leq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(caps_dist_geq(X,_,_)), V0!=X.").

%bias declarations to add rule penalties (bias search towards more general rules)
#bias("penalty(2, head(X)) :- in_head(X).").
#bias("penalty(1, body(X)) :- in_body(X).").