#pos(ex1@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). ghost(east, 9). food(west, 5). food(west, 10). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 7). ghost(east, 6). food(east, 8). food(east, 6). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 7). capsule(east, 9). capsule(east, 4).}).
#pos(ex2@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 6). capsule(east, 10). ghost(east, 8.0). food(east, 8). capsule(east, 5). ghost(west, 9.0). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 2). food(west, 7).}).
#pos(ex3@0, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 10.0). capsule(west, 5). food(west, 8). food(east, 9). food(west, 4). food(east, 8). ghost(west, 7.0). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6).}).
#pos(ex4@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 10.0). food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). food(west, 5). food(east, 10). food(north, 1). ghost(west, 5.0). capsule(east, 7). capsule(west, 4). food(west, 6).}).
#pos(ex5@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 10.0). food(west, 4). wall(north). capsule(west, 3). food(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 8). food(west, 5). food(east, 10). ghost(east, 5.0). food(west, 6).}).
#pos(ex6@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 10.0). food(west, 4). capsule(north, 2). food(east, 3). wall(north). food(west, 3). wall(east). wall(south). wall(west). food(west, 2). food(west, 1). food(west, 5). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex7@1, {move(west)}, {move(south), move(north), move(east)}, {food(north, 4). ghost(east, 10.0). food(west, 4). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 10). ghost(east, 5.0). capsule(east, 3). food(east, 4).}).
#pos(ex8@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 10.0). wall(north). wall(east). wall(west). food(east, 5). wall(south). food(north, 3). food(north, 2). food(north, 1). ghost(east, 5.0). capsule(east, 4).}).
#pos(ex9@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 10.0). wall(north). wall(east). wall(west). wall(south). capsule(east, 10). food(north, 2). food(north, 1). ghost(east, 5.0). capsule(east, 3). food(east, 4).}).
#pos(ex10@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 10.0). capsule(east, 2). wall(north). food(east, 3). wall(east). wall(west). food(east, 5). wall(south). food(north, 1). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex11@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 10.0). wall(north). wall(east). food(east, 2). wall(west). wall(south). food(east, 6). ghost(east, 5.0). capsule(east, 3). capsule(east, 10).}).
#pos(ex12@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 10.0). wall(north). wall(east). ghost(east, 9.0). wall(west). wall(south). capsule(east, 4). ghost(east, 5.0). food(east, 1). food(east, 7).}).
#pos(ex13@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 8.0). wall(north). wall(east). wall(west). wall(south). ghost(east, 7.0). food(east, 6). ghost(west, 5.0). capsule(east, 3). capsule(east, 10).}).
#pos(ex14@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 6.0). ghost(west, 5.0). wall(north). wall(east). capsule(south, 2). wall(south). food(east, 5). wall(west). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex15@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). ghost(east, 4.0). wall(north). capsule(west, 3). wall(east). wall(west). wall(south). capsule(east, 8). food(east, 10). ghost(west, 5.0). food(east, 4).}).
#pos(ex16@1, {move(west)}, {move(south), move(north), move(east)}, {food(east, 9). food(south, 3). wall(north). ghost(south, 2.0). wall(east). wall(west). wall(south). ghost(east, 1.0). food(east, 10). ghost(west, 5.0). capsule(east, 7). capsule(west, 4).}).
#pos(ex17@1, {move(west)}, {move(south), move(north), move(east)}, {wall(north). ghost(west, 3.0). capsule(west, 3). wall(east). ghost(east, 2.0). wall(west). wall(south). ghost(east, 1.0). capsule(east, 8). food(east, 10). food(east, 4).}).
#pos(ex18@1, {move(south)}, {move(north), move(east), move(west)}, {wall(north). wall(east). capsule(south, 2). ghost(east, 2.0). food(east, 5). wall(south). ghost(east, 1.0). wall(west). capsule(east, 9). ghost(west, 1.0).}).
#pos(ex19@1, {move(south)}, {move(north), move(east), move(west)}, {wall(north). wall(east). ghost(north, 1.0). ghost(east, 2.0). wall(south). wall(west). capsule(east, 8). capsule(south, 1). food(east, 4).}).
#pos(ex20@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(west, 4.0). wall(north). food(east, 3). wall(east). ghost(north, 1.0). wall(south). wall(west). ghost(east, 4.0). capsule(east, 7).}).
#pos(ex21@3, {move(north)}, {move(south), move(east), move(west)}, {wall(north). ghost(east, 3.5). wall(east). wall(south). wall(west). ghost(east, 7.0). capsule(east, 8). ghost(west, 2.5). food(east, 4).}).
#pos(ex22@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). wall(north). ghost(west, 3.0). wall(east). wall(south). food(east, 5). wall(west). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex23@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). wall(north). wall(east). ghost(east, 2.5). wall(west). wall(south). capsule(east, 8). food(east, 10). ghost(west, 4.5). food(east, 4).}).
#pos(ex24@3, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). food(south, 3). wall(north). wall(east). ghost(west, 6.0). ghost(east, 2.0). wall(west). wall(south). ghost(east, 1.0). food(east, 10). capsule(east, 7).}).
#pos(ex25@3, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). wall(north). ghost(east, 3.5). wall(east). food(south, 2). ghost(west, 5.5). ghost(north, 1.0). wall(west). wall(south). capsule(east, 6). food(east, 10).}).
#pos(ex26@3, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). ghost(west, 5.0). wall(north). wall(east). ghost(north, 1.0). wall(west). wall(south). food(south, 1). capsule(east, 5). food(east, 10). ghost(east, 5.0). capsule(east, 10).}).
#pos(ex27@3, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). wall(north). ghost(east, 6.5). wall(east). ghost(north, 1.0). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(west, 4.5).}).
#pos(ex28@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). ghost(east, 8.0). food(east, 9). wall(north). wall(east). ghost(north, 1.0). wall(west). wall(south). food(east, 10). capsule(east, 7).}).
#pos(ex29@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). wall(north). wall(east). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(west, 4.5). ghost(east, 7.5). ghost(west, 1.0).}).
#pos(ex30@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). wall(north). wall(east). ghost(west, 1.0). wall(west). wall(south). ghost(east, 7.0). capsule(east, 5). capsule(east, 10). food(east, 10). ghost(west, 5.0). food(east, 7).}).
#pos(ex31@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). wall(north). ghost(east, 6.5). wall(east). ghost(west, 5.5). ghost(west, 1.0). wall(west). wall(south). capsule(east, 4). food(east, 10). capsule(east, 9). food(east, 6). food(east, 7).}).
#pos(ex32@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 6.0). food(east, 9). food(east, 8). wall(north). wall(east). ghost(west, 1.0). ghost(west, 6.0). wall(west). food(east, 5). wall(south). capsule(east, 8). food(east, 10). capsule(east, 3). food(east, 6). food(east, 7).}).
#pos(ex33@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 7). food(east, 9). food(east, 8). capsule(north, 2). wall(north). ghost(west, 3.0). wall(east). ghost(east, 5.5). wall(west). food(east, 5). food(east, 10). wall(south). ghost(west, 6.5). food(east, 6). capsule(east, 7). food(east, 4).}).
#pos(ex34@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). ghost(west, 5.0). food(east, 3). ghost(west, 7.0). capsule(west, 3). wall(east). wall(north). wall(west). food(east, 5). food(east, 10). wall(south). capsule(east, 6). food(east, 6). ghost(east, 5.0). food(east, 4). food(east, 7).}).
#pos(ex35@3, {move(north)}, {move(south), move(east), move(west)}, {food(east, 9). food(east, 8). capsule(west, 4). food(east, 3). wall(north). wall(east). food(east, 2). ghost(north, 3.5). food(east, 5). wall(west). wall(south). capsule(east, 5). food(east, 6). ghost(west, 5.0). ghost(west, 7.5). food(east, 4). food(east, 7).}).
#pos(ex36@3, {move(north)}, {move(south), move(east), move(west)}, {food(east, 7). ghost(west, 4.0). food(east, 8). wall(north). food(east, 3). capsule(west, 3). wall(east). food(east, 2). wall(west). food(east, 5). wall(south). food(east, 6). ghost(north, 1.5). ghost(west, 7.5). capsule(east, 4). food(east, 4).}).
#pos(ex37@5, {move(north)}, {move(south), move(east), move(west)}, {food(east, 7). ghost(west, 4.0). wall(north). food(east, 3). wall(east). food(east, 2). wall(west). food(east, 5). wall(south). ghost(west, 8.0). capsule(west, 2). food(east, 6). capsule(east, 3). food(east, 4).}).
#pos(ex38@5, {move(north)}, {move(south), move(east), move(west)}, {wall(north). food(east, 3). capsule(west, 3). wall(east). food(east, 2). ghost(west, 6.0). wall(west). food(east, 5). wall(south). ghost(west, 8.5). capsule(east, 4). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex39@5, {move(east)}, {move(south), move(north), move(west)}, {food(east, 8). wall(north). food(east, 3). wall(east). food(east, 2). wall(west). food(east, 5). wall(south). ghost(west, 8.0). capsule(east, 5). food(east, 6). capsule(west, 4). ghost(west, 9.0). food(east, 4). food(east, 7).}).
#pos(ex40@5, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 9.5). capsule(west, 5). wall(north). food(east, 3). wall(east). food(east, 2). food(east, 1). wall(west). food(east, 5). wall(south). ghost(west, 8.0). capsule(east, 4). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex41@5, {move(south)}, {move(north), move(east), move(west)}, {food(south, 3). food(east, 3). ghost(west, 10.0). wall(east). capsule(east, 3). food(south, 2). wall(north). food(east, 2). wall(west). food(east, 5). food(south, 1). wall(south). ghost(west, 8.0). food(east, 6). capsule(west, 6). food(south, 4). food(east, 1). food(east, 4).}).
#pos(ex42@5, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 9.5). capsule(west, 5). capsule(east, 2). food(south, 3). food(east, 3). wall(north). wall(east). food(south, 2). food(east, 2). wall(west). food(east, 5). food(south, 1). wall(south). ghost(west, 8.0). food(east, 4).}).
#pos(ex43@5, {move(south)}, {move(north), move(east), move(west)}, {wall(north). food(east, 3). wall(east). food(south, 2). food(east, 2). capsule(east, 1). wall(west). food(east, 5). food(south, 1). wall(south). ghost(west, 8.0). capsule(west, 4). food(east, 4).}).
#pos(ex44@5, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). capsule(east, 2). wall(north). food(east, 3). ghost(west, 10.0). wall(east). food(east, 2). ghost(west, 6.0). wall(west). food(east, 5). food(south, 1). wall(south). food(east, 6). food(east, 1). food(east, 4).}).
#pos(ex45@6, {move(south)}, {move(north), move(east), move(west)}, {wall(north). food(east, 3). ghost(west, 10.0). wall(east). food(east, 2). ghost(west, 6.0). wall(west). food(east, 5). food(west, 2). food(south, 1). food(north, 3). wall(south). capsule(west, 6). capsule(north, 1). food(east, 4).}).
#pos(ex46@6, {move(west)}, {move(south), move(north), move(east)}, {food(north, 4). ghost(west, 4.0). capsule(north, 2). food(east, 3). wall(north). wall(east). wall(west). food(east, 5). wall(south). food(west, 1). capsule(west, 7). food(east, 6). food(east, 4).}).
#pos(ex47@6, {move(north)}, {move(south), move(east), move(west)}, {wall(north). wall(east). ghost(west, 2.0). wall(west). food(east, 5). wall(south). food(east, 6). capsule(west, 6). capsule(east, 3). food(east, 4). food(east, 7).}).
#pos(ex48@6, {move(north)}, {move(south), move(east), move(west)}, {capsule(west, 5). capsule(east, 2). wall(north). food(east, 3). wall(east). ghost(west, 2.0). wall(west). food(east, 5). wall(south). food(east, 6). food(east, 4).}).
#pos(ex49@6, {move(north)}, {move(south), move(east), move(west)}, {wall(north). food(east, 3). ghost(west, 10.0). wall(east). ghost(west, 2.0). capsule(east, 1). wall(west). food(east, 5). wall(south). capsule(west, 4). food(east, 4).}).
#pos(ex50@6, {move(north)}, {move(south), move(east), move(west)}, {capsule(west, 5). capsule(east, 2). wall(north). food(east, 3). wall(east). ghost(west, 2.0). food(east, 2). wall(west). food(east, 5). wall(south). ghost(west, 8.0). food(east, 4).}).
#pos(ex51@6, {move(east)}, {move(south), move(north), move(west)}, {wall(north). food(east, 3). wall(east). ghost(west, 2.0). food(east, 2). ghost(west, 6.0). wall(west). food(east, 5). wall(south). food(east, 6). capsule(west, 6). capsule(east, 3). food(east, 1). food(east, 4).}).
#pos(ex52@6, {move(east)}, {move(south), move(north), move(west)}, {wall(north). food(east, 3). wall(east). ghost(west, 2.0). food(east, 2). ghost(west, 6.0). capsule(south, 2). food(east, 5). wall(west). wall(south). capsule(west, 7). food(east, 1). food(east, 4).}).
#pos(ex53@6, {move(east)}, {move(south), move(north), move(west)}, {wall(north). food(east, 3). capsule(west, 3). wall(east). capsule(west, 8). ghost(west, 2.0). ghost(west, 6.0). food(east, 2). wall(west). wall(south). food(east, 1). food(east, 4).}).
#pos(ex54@6, {move(south)}, {move(north), move(east), move(west)}, {food(south, 3). wall(north). capsule(west, 9). wall(east). ghost(west, 2.0). food(south, 2). ghost(west, 6.0). wall(west). wall(south). food(south, 1). capsule(west, 4).}).
#pos(ex55@6, {move(south)}, {move(north), move(east), move(west)}, {wall(north). capsule(west, 3). wall(east). capsule(west, 8). ghost(west, 2.0). food(south, 2). ghost(west, 6.0). wall(west). wall(south). food(south, 1).}).
#pos(ex56@6, {move(south)}, {move(north), move(east), move(west)}, {wall(north). ghost(north, 2.0). wall(east). ghost(west, 6.0). wall(west). wall(south). food(south, 1). capsule(west, 7). capsule(west, 2).}).
#pos(ex57@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). ghost(east, 9). food(west, 5). food(west, 10). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 7). ghost(east, 6). food(east, 8). food(east, 6). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 7). capsule(east, 9). capsule(east, 4).}).
#pos(ex58@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 6). capsule(east, 10). food(east, 8). capsule(east, 5). ghost(west, 9.0). food(east, 7). ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 2). food(west, 7).}).
#pos(ex59@0, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). food(west, 8). food(east, 9). food(west, 4). food(east, 8). ghost(west, 7.0). ghost(east, 6.0). food(west, 3). wall(east). wall(north). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6).}).
#pos(ex60@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). food(west, 5). food(east, 10). food(north, 1). ghost(west, 5.0). capsule(east, 7). capsule(west, 4). food(west, 6).}).
#pos(ex61@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). wall(north). ghost(west, 3.0). food(west, 3). capsule(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 8). food(west, 5). food(east, 10). food(west, 6).}).
#pos(ex62@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 6.0). food(west, 4). capsule(north, 2). food(east, 3). wall(north). food(west, 3). wall(east). wall(south). wall(west). food(west, 2). food(west, 1). food(west, 5). capsule(east, 9). ghost(west, 1.0).}).
#pos(ex63@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). wall(north). capsule(west, 3). food(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). capsule(east, 8). food(west, 5). food(east, 10). ghost(east, 4.0). food(west, 6). ghost(west, 1.0).}).
#pos(ex64@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). ghost(north, 2.0). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(north, 1). capsule(east, 7). capsule(west, 4). food(west, 6). ghost(west, 1.0).}).
#pos(ex65@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). food(west, 8). food(east, 9). food(east, 8). food(west, 4). wall(north). wall(east). ghost(west, 2.0). wall(west). wall(south). food(west, 2). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6). ghost(west, 1.0).}).
#pos(ex66@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 8). food(east, 9). food(east, 8). wall(north). food(west, 3). food(west, 9). ghost(west, 2.0). wall(east). ghost(west, 1.0). ghost(east, 9.0). wall(west). wall(south). food(west, 5). capsule(east, 5). capsule(east, 10). food(east, 10). capsule(west, 6). food(west, 7). food(west, 6). food(east, 7).}).
#pos(ex67@1, {move(east)}, {move(south), move(north), move(west)}, {wall(east). wall(west). wall(south). food(west, 10). food(east, 10). food(west, 6). food(west, 8). food(west, 9). ghost(west, 2.0). capsule(west, 7). ghost(west, 1.0). food(east, 8). ghost(east, 7.0). food(east, 6). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 7). capsule(east, 9). capsule(east, 4).}).
#pos(ex68@1, {move(east)}, {move(south), move(north), move(west)}, {wall(east). capsule(west, 8). wall(west). food(east, 5). wall(south). food(west, 5). food(west, 10). food(east, 10). ghost(east, 5.0). food(west, 8). food(west, 9). ghost(west, 2.0). ghost(west, 1.0). food(east, 8). food(east, 6). food(east, 7). food(east, 9). wall(north). capsule(east, 8). food(west, 7). capsule(east, 3).}).
#pos(ex69@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(north, 2). wall(east). wall(west). food(east, 5). wall(south). food(east, 10). food(west, 10). food(west, 6). food(west, 8). food(west, 9). ghost(west, 2.0). ghost(west, 1.0). food(east, 8). capsule(west, 9). food(east, 6). capsule(east, 7). food(east, 7). food(east, 4). food(east, 9). wall(north). ghost(west, 5.0).}).
#pos(ex70@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). wall(east). wall(west). food(east, 5). wall(south). food(east, 10). food(west, 10). ghost(west, 7.0). food(west, 9). ghost(west, 1.0). food(east, 8). capsule(east, 6). food(east, 6). food(east, 7). food(east, 4). food(east, 9). wall(north). food(east, 3). capsule(west, 3). capsule(west, 10). food(west, 7).}).
#pos(ex71@1, {move(north)}, {move(south), move(east), move(west)}, {food(east, 7). food(west, 8). food(east, 9). food(east, 8). wall(north). food(east, 3). wall(east). food(east, 2). ghost(west, 1.0). ghost(west, 6.0). food(east, 5). wall(west). wall(south). capsule(east, 5). food(west, 10). capsule(west, 4). ghost(west, 9.0). food(east, 6). food(east, 4).}).
#pos(ex72@1, {move(north)}, {move(south), move(east), move(west)}, {food(east, 7). ghost(west, 4.0). food(east, 8). ghost(south, 1.0). food(east, 3). capsule(west, 3). wall(east). capsule(west, 10). wall(north). food(east, 2). wall(west). food(east, 5). wall(south). food(east, 6). food(west, 7). ghost(west, 9.0). capsule(east, 4). food(east, 4).}).
#pos(ex73@1, {move(north)}, {move(south), move(east), move(west)}, {food(east, 7). food(west, 8). ghost(south, 1.0). food(east, 3). capsule(west, 9). wall(east). wall(north). ghost(west, 2.0). food(east, 2). wall(west). food(east, 5). wall(south). capsule(west, 2). food(east, 6). capsule(east, 3). ghost(west, 9.0). food(east, 4).}).
#pos(ex74@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(west, 4.0). ghost(west, 7.0). ghost(south, 1.0). food(east, 3). capsule(west, 3). wall(east). food(west, 9). capsule(west, 10). wall(north). food(east, 2). wall(west). food(east, 5). wall(south). capsule(east, 4). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex75@1, {move(east)}, {move(south), move(north), move(west)}, {food(east, 8). ghost(south, 1.0). food(east, 3). wall(north). wall(east). food(east, 2). ghost(west, 6.0). wall(west). food(east, 5). wall(south). capsule(east, 5). food(west, 10). food(east, 4). capsule(west, 4). ghost(west, 9.0). food(east, 6). food(east, 7).}).
#pos(ex76@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). wall(north). food(east, 3). wall(east). food(east, 2). food(east, 1). ghost(west, 1.0). food(east, 5). wall(west). wall(south). ghost(west, 8.0). capsule(east, 4). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex77@1, {move(east)}, {move(south), move(north), move(west)}, {food(south, 3). food(east, 3). ghost(west, 3.0). ghost(west, 10.0). capsule(east, 3). food(south, 2). wall(east). food(east, 2). wall(north). wall(west). food(east, 5). food(south, 1). wall(south). food(east, 6). capsule(west, 6). food(south, 4). food(east, 1). food(east, 4).}).
#pos(ex78@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). food(south, 3). food(east, 3). ghost(west, 10.0). food(west, 3). wall(east). wall(north). food(east, 2). capsule(south, 2). wall(west). food(east, 5). food(west, 2). wall(south). food(west, 5). capsule(west, 7). ghost(west, 5.0). food(south, 4). food(east, 1). food(east, 4).}).
#pos(ex79@1, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). ghost(west, 7.0). food(east, 3). ghost(west, 10.0). food(west, 3). capsule(west, 8). capsule(west, 3). wall(east). food(east, 2). wall(north). wall(west). wall(south). food(west, 5). food(west, 6). food(east, 1). food(east, 4).}).
#pos(ex80@1, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). food(south, 3). ghost(west, 10.0). capsule(west, 9). wall(east). wall(north). food(south, 2). wall(west). wall(south). food(south, 1). food(west, 5). ghost(west, 9.0). food(west, 7). capsule(west, 4). food(west, 6).}).
#pos(ex81@1, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). wall(north). capsule(west, 3). food(west, 3). capsule(west, 8). food(south, 2). wall(east). wall(west). wall(south). food(south, 1). food(west, 5). ghost(west, 8.0). food(west, 6).}).
#pos(ex82@1, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(south, 1). food(west, 5). ghost(west, 8.0). capsule(west, 7). capsule(west, 2). ghost(west, 9.0).}).
#pos(ex83@1, {move(north)}, {move(south), move(east), move(west)}, {food(west, 4). wall(north). ghost(west, 10.0). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). wall(west). wall(south). food(west, 2). food(west, 5). ghost(west, 9.0).}).
#pos(ex84@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(west, 7.0). food(west, 4). ghost(west, 10.0). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 5). capsule(west, 7). capsule(west, 2).}).
#pos(ex85@1, {move(north)}, {move(south), move(east), move(west)}, {food(west, 4). food(west, 6). wall(north). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). wall(west). wall(south). food(west, 5). ghost(west, 9.0).}).
#pos(ex86@1, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). wall(north). capsule(west, 9). wall(east). wall(west). wall(south). food(west, 5). food(west, 7). capsule(west, 4). food(west, 6).}).
#pos(ex87@1, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). wall(north). ghost(west, 10.0). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). wall(west). wall(south). food(west, 5). food(west, 6).}).
#pos(ex88@1, {move(west)}, {move(south), move(north), move(east)}, {food(west, 4). food(south, 3). wall(north). food(west, 3). wall(east). capsule(south, 2). wall(west). wall(south). food(west, 2). food(west, 5). ghost(west, 8.0). capsule(west, 7). food(south, 4).}).
#pos(ex89@1, {move(south)}, {move(north), move(east), move(west)}, {food(south, 3). wall(north). wall(east). capsule(east, 3). food(south, 2). ghost(west, 6.0). wall(west). food(east, 5). food(south, 1). wall(south). capsule(west, 6). food(south, 4). ghost(west, 9.0). food(east, 4).}).
#pos(ex90@1, {move(south)}, {move(north), move(east), move(west)}, {capsule(west, 5). capsule(east, 2). ghost(west, 4.0). ghost(west, 7.0). food(south, 3). food(east, 3). wall(north). wall(east). food(south, 2). wall(west). wall(south). food(south, 1). ghost(west, 9.0). food(east, 4).}).
#pos(ex91@1, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 7.0). wall(north). food(east, 3). wall(east). food(south, 2). ghost(west, 2.0). food(east, 2). capsule(east, 1). wall(west). wall(south). food(south, 1). food(west, 10). ghost(west, 5.0). capsule(west, 4).}).
#pos(ex92@1, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). capsule(east, 2). ghost(west, 4.0). wall(north). wall(east). food(west, 9). food(east, 2). wall(west). wall(south). food(south, 1). ghost(west, 5.0). food(east, 1).}).
#pos(ex93@2, {move(south)}, {move(north), move(east), move(west)}, {ghost(west, 7.0). wall(north). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 2). food(south, 1). food(west, 10). capsule(west, 6). ghost(west, 5.0). capsule(north, 1).}).
#pos(ex94@2, {move(west)}, {move(south), move(north), move(east)}, {capsule(north, 2). wall(north). ghost(west, 3.0). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 1). capsule(west, 7). ghost(west, 9.0).}).
#pos(ex95@2, {move(north)}, {move(south), move(east), move(west)}, {ghost(west, 7.0). wall(north). ghost(west, 3.0). wall(east). wall(west). wall(south). ghost(north, 4.0). food(west, 10). capsule(west, 6). capsule(east, 3).}).
#pos(ex96@2, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). capsule(east, 2). ghost(west, 4.0). wall(north). wall(east). food(west, 9). ghost(north, 1.0). wall(west). wall(south). ghost(west, 8.0).}).
#pos(ex97@2, {move(west)}, {move(south), move(north), move(east)}, {wall(north). wall(east). ghost(north, 1.0). ghost(west, 6.0). wall(west). wall(south). ghost(west, 8.0). food(west, 10). capsule(west, 6). capsule(north, 1).}).
#pos(ex98@2, {move(north)}, {move(south), move(east), move(west)}, {capsule(west, 5). capsule(east, 2). ghost(west, 4.0). wall(north). wall(east). food(west, 9). ghost(west, 6.0). wall(west). wall(south). ghost(east, 1.0).}).
#pos(ex99@2, {move(east)}, {move(south), move(north), move(west)}, {ghost(south, 1.0). wall(north). ghost(north, 2.0). wall(east). ghost(west, 6.0). capsule(east, 1). wall(west). wall(south). food(west, 10). capsule(west, 4).}).
#pos(ex100@2, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). wall(north). ghost(south, 2.0). wall(east). wall(west). wall(south). ghost(west, 5.0). ghost(west, 1.0).}).
#pos(ex101@4, {move(north)}, {move(south), move(east), move(west)}, {wall(north). wall(east). ghost(west, 3.5). ghost(east, 2.5). wall(west). wall(south). food(west, 10). capsule(west, 4).}).
#pos(ex102@4, {move(north)}, {move(south), move(east), move(west)}, {capsule(west, 5). ghost(east, 3.0). ghost(west, 4.0). wall(north). wall(east). wall(west). wall(south).}).
#pos(ex103@4, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 6). ghost(east, 3.5). ghost(west, 10.0). wall(east). wall(north). wall(west). wall(south). ghost(west, 4.5).}).
#pos(ex104@4, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). wall(north). ghost(west, 3.0). wall(east). wall(west). wall(south). ghost(west, 8.0). ghost(east, 4.0).}).
#pos(ex105@4, {move(west)}, {move(south), move(north), move(east)}, {wall(north). ghost(east, 4.5). wall(east). ghost(west, 6.0). wall(west). wall(south). food(west, 10). ghost(south, 1.5). capsule(west, 4).}).
#pos(ex106@4, {move(east)}, {move(south), move(north), move(west)}, {ghost(west, 4.0). wall(north). capsule(west, 3). wall(east). food(west, 9). capsule(west, 10). ghost(east, 2.0). wall(west). wall(south). ghost(east, 5.0).}).
#pos(ex107@6, {move(west)}, {move(south), move(north), move(east)}, {ghost(west, 4.0). wall(north). ghost(east, 4.5). wall(east). wall(west). wall(south). ghost(east, 9). food(west, 10). capsule(west, 4).}).
#pos(ex108@6, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 8.0). wall(north). capsule(west, 3). ghost(east, 6.5). food(west, 9). capsule(west, 10). wall(east). wall(west). wall(south). ghost(west, 1.0).}).
#pos(ex109@6, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 6.0). wall(north). wall(east). wall(west). wall(south). food(west, 10). capsule(west, 4). ghost(west, 1.0).}).
#pos(ex110@6, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). wall(north). wall(east). ghost(east, 5.5). wall(west). wall(south). ghost(east, 4.0). ghost(west, 1.0).}).
#pos(ex111@6, {move(south)}, {move(north), move(east), move(west)}, {wall(north). wall(east). ghost(east, 2.0). wall(west). wall(south). capsule(west, 6). ghost(east, 5.0). ghost(west, 1.0).}).
#pos(ex112@5, {move(south)}, {move(north), move(east), move(west)}, {capsule(west, 5). wall(north). ghost(east, 3.5). wall(east). ghost(north, 1.0). ghost(east, 2.0). wall(west). wall(south).}).
#pos(ex113@5, {move(east)}, {move(south), move(north), move(west)}, {wall(north). ghost(south, 2.0). ghost(north, 2.0). wall(east). ghost(north, 1.0). wall(west). wall(south). food(west, 10). capsule(west, 4).}).
#pos(ex114@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). ghost(east, 9). food(west, 5). food(west, 10). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 7). ghost(east, 6). food(east, 8). food(east, 6). food(east, 7). food(east, 9). food(west, 4). wall(north). food(west, 7). capsule(east, 9). capsule(east, 4).}).
#pos(ex115@0, {move(west)}, {move(south), move(north), move(east)}, {food(west, 3). wall(east). wall(west). wall(south). food(west, 5). food(east, 10). food(west, 6). food(west, 8). food(west, 9). capsule(west, 6). capsule(east, 10). food(east, 8). capsule(east, 5). ghost(west, 9.0). food(east, 7). ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 2). food(west, 7).}).
#pos(ex116@0, {move(west)}, {move(south), move(north), move(east)}, {capsule(west, 5). food(west, 8). food(east, 9). food(west, 4). food(east, 8). ghost(west, 7.0). ghost(east, 6.0). food(west, 3). wall(east). wall(north). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 6). food(west, 5). food(east, 10). food(west, 7). food(west, 6).}).
#pos(ex117@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(east, 9). food(west, 4). wall(north). food(west, 3). food(west, 7). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). food(west, 5). food(east, 10). food(north, 1). ghost(west, 5.0). capsule(east, 7). capsule(west, 4). food(west, 6).}).
#pos(ex118@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). wall(north). capsule(west, 3). food(west, 3). wall(east). food(east, 2). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 8). food(west, 5). food(east, 10). ghost(east, 5.0). food(west, 6).}).
#pos(ex119@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 6.0). food(west, 4). capsule(north, 2). food(east, 3). wall(north). food(west, 3). wall(east). wall(south). wall(west). food(west, 2). food(west, 1). food(west, 5). ghost(east, 5.0). capsule(east, 9).}).
#pos(ex120@1, {move(east)}, {move(south), move(north), move(west)}, {food(north, 4). ghost(east, 6.0). food(west, 4). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 10). ghost(east, 5.0). capsule(east, 3). food(east, 4).}).
#pos(ex121@1, {move(west)}, {move(south), move(north), move(east)}, {ghost(east, 3.0). food(west, 4). capsule(north, 2). food(east, 3). wall(north). food(west, 3). wall(east). wall(south). wall(west). food(west, 2). food(west, 5). ghost(east, 4.0). capsule(east, 9).}).
#pos(ex122@1, {move(west)}, {move(south), move(north), move(east)}, {food(north, 4). ghost(east, 3.0). food(west, 4). wall(north). food(west, 3). wall(east). wall(west). wall(south). food(west, 2). food(west, 1). capsule(east, 10). ghost(east, 4.0). capsule(east, 3). food(east, 4).}).
#pos(ex123@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). wall(north). wall(east). wall(west). food(east, 5). wall(south). food(north, 3). food(north, 2). food(north, 1). ghost(east, 4.0). capsule(east, 4).}).
#pos(ex124@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). wall(north). wall(east). wall(west). wall(south). capsule(east, 10). food(north, 2). food(north, 1). ghost(east, 4.0). capsule(east, 3). food(east, 4).}).
#pos(ex125@1, {move(south)}, {move(north), move(east), move(west)}, {capsule(east, 2). ghost(east, 3.0). wall(north). food(east, 3). wall(east). wall(west). food(east, 5). wall(south). food(north, 1). ghost(east, 4.0). capsule(east, 9).}).
#pos(ex126@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(south, 1.0). wall(north). wall(east). ghost(east, 2.0). wall(west). wall(south). capsule(east, 10). food(north, 2). capsule(east, 3). food(east, 4).}).
#pos(ex127@1, {move(north)}, {move(south), move(east), move(west)}, {capsule(east, 2). ghost(south, 1.0). food(east, 3). ghost(south, 2.0). wall(east). wall(north). ghost(east, 9.0). wall(west). food(east, 5). wall(south). food(north, 1). capsule(east, 9).}).
#pos(ex128@1, {move(north)}, {move(south), move(east), move(west)}, {ghost(south, 1.0). wall(north). ghost(south, 2.0). wall(east). food(east, 2). wall(west). wall(south). ghost(east, 7.0). food(east, 6). capsule(east, 3). capsule(east, 10).}).
#pos(ex129@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(south, 1.0). wall(north). ghost(south, 2.0). wall(east). wall(west). wall(south). capsule(east, 4). ghost(east, 5.0). food(east, 1). food(east, 7).}).
#pos(ex130@1, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). wall(north). wall(east). ghost(west, 2.0). wall(west). wall(south). capsule(east, 10). food(east, 6). capsule(east, 3). ghost(west, 1.0).}).
#pos(ex131@1, {move(south)}, {move(north), move(east), move(west)}, {wall(north). wall(east). ghost(west, 2.0). capsule(south, 2). wall(south). food(east, 5). wall(west). ghost(east, 1.0). capsule(east, 9). ghost(west, 1.0).}).
#pos(ex132@1, {move(south)}, {move(north), move(east), move(west)}, {wall(north). wall(east). ghost(west, 2.0). ghost(north, 1.0). wall(south). wall(west). capsule(east, 8). capsule(south, 1). food(east, 4).}).
#pos(ex133@3, {move(north)}, {move(south), move(east), move(west)}, {ghost(west, 4). wall(north). food(east, 3). wall(east). ghost(west, 3.5). ghost(east, 2.5). wall(south). wall(west). capsule(east, 7).}).
#pos(ex134@3, {move(north)}, {move(south), move(east), move(west)}, {wall(north). ghost(west, 3.0). wall(east). ghost(east, 2.5). wall(south). wall(west). capsule(east, 8). ghost(west, 2.5). food(east, 4).}).
#pos(ex135@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). ghost(west, 4.0). wall(north). wall(east). wall(south). food(east, 5). wall(west). ghost(west, 5.0). capsule(east, 9).}).
#pos(ex136@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 3.0). wall(north). wall(east). ghost(west, 6.0). wall(west). wall(south). capsule(east, 8). food(east, 10). food(east, 4). ghost(south, 4.0).}).
#pos(ex137@3, {move(south)}, {move(north), move(east), move(west)}, {food(east, 9). food(south, 3). wall(north). wall(east). wall(west). wall(south). ghost(south, 3.0). ghost(west, 8.0). food(east, 10). capsule(east, 7).}).
#pos(ex138@3, {move(north)}, {move(south), move(east), move(west)}, {food(east, 9). ghost(south, 1.0). ghost(south, 2.5). wall(north). wall(east). food(south, 2). wall(west). wall(south). capsule(east, 6). ghost(west, 6.5). food(east, 10).}).
#pos(ex139@3, {move(west)}, {move(south), move(north), move(east)}, {food(east, 9). ghost(west, 7.0). ghost(south, 1.0). food(south, 3). wall(north). wall(east). wall(west). wall(south). food(east, 10). capsule(east, 7). ghost(south, 4.0).}).
#pos(ex140@3, {move(west)}, {move(south), move(north), move(east)}, {wall(north). wall(east). ghost(west, 5.5). ghost(east, 5.5). wall(west). wall(south). ghost(east, 1.0). capsule(east, 8). food(east, 10). food(east, 4).}).
#pos(ex141@3, {move(west)}, {move(south), move(north), move(east)}, {wall(north). wall(east). wall(south). food(east, 5). wall(west). ghost(east, 7.0). ghost(east, 1.0). capsule(east, 9). ghost(south, 4.0).}).
#pos(ex142@3, {move(west)}, {move(south), move(north), move(east)}, {wall(north). ghost(east, 8.5). wall(east). ghost(east, 5.5). wall(west). wall(south). ghost(east, 1.0). food(east, 6). capsule(east, 10).}).
#pos(ex143@3, {move(south)}, {move(north), move(east), move(west)}, {ghost(east, 10.0). wall(north). wall(east). wall(west). wall(south). ghost(east, 7.0). ghost(east, 1.0). food(east, 7).}).
#pos(ex144@3, {move(south)}, {move(north), move(east), move(west)}, {wall(north). ghost(east, 6.5). wall(east). ghost(north, 1.0). wall(west). wall(south). food(east, 6). ghost(east, 9.5). capsule(east, 10).}).
#pos(ex145@3, {move(south)}, {move(north), move(east), move(west)}, {ghost(east, 6.0). wall(north). wall(east). ghost(north, 1.0). ghost(east, 9.0). wall(west). food(east, 5). wall(south). capsule(east, 9).}).
#pos(ex146@3, {move(south)}, {move(north), move(east), move(west)}, {wall(north). ghost(east, 8.5). wall(east). ghost(east, 5.5). ghost(north, 1.0). wall(west). wall(south). food(east, 4). capsule(east, 10).}).
#pos(ex147@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 8.0). wall(north). wall(east). ghost(north, 1.0). wall(west). food(east, 5). wall(south). ghost(east, 5.0).}).
#pos(ex148@3, {move(east)}, {move(south), move(north), move(west)}, {wall(north). ghost(east, 4.5). wall(east). ghost(west, 1.0). wall(west). wall(south). ghost(east, 7.5). food(east, 4). capsule(east, 10).}).
#pos(ex149@3, {move(east)}, {move(south), move(north), move(west)}, {wall(north). food(east, 3). wall(east). wall(south). wall(west). ghost(east, 7.0). ghost(east, 4.0). capsule(east, 9). ghost(west, 1.0).}).
#pos(ex150@3, {move(east)}, {move(south), move(north), move(west)}, {wall(north). ghost(east, 3.5). ghost(east, 6.5). wall(east). food(east, 2). wall(west). wall(south). capsule(east, 8). food(east, 10). ghost(west, 1.0).}).
#pos(ex151@3, {move(north)}, {move(south), move(east), move(west)}, {ghost(east, 3.0). ghost(east, 6.0). food(east, 9). wall(north). wall(east). wall(west). wall(south). food(east, 10). food(north, 1). capsule(east, 7). ghost(west, 1.0).}).
#pos(ex152@3, {move(north)}, {move(south), move(east), move(west)}, {food(east, 9). ghost(south, 1.0). wall(north). wall(east). ghost(east, 2.5). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(east, 7.5).}).
#pos(ex153@3, {move(north)}, {move(south), move(east), move(west)}, {food(east, 9). ghost(south, 1.0). wall(north). wall(east). ghost(east, 9.0). wall(west). wall(south). capsule(east, 5). food(east, 10). ghost(east, 4.0). capsule(east, 10).}).
#pos(ex154@3, {move(north)}, {move(south), move(east), move(west)}, {food(east, 9). ghost(south, 1.0). wall(north). wall(east). ghost(east, 5.5). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(east, 9.5).}).
#pos(ex155@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 10.0). food(east, 9). ghost(south, 1.0). wall(north). wall(east). wall(west). wall(south). ghost(east, 7.0). food(east, 10). capsule(east, 7).}).
#pos(ex156@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). wall(north). ghost(east, 8.5). ghost(east, 6.5). wall(east). wall(west). wall(south). capsule(east, 6). food(east, 10). ghost(west, 1.0).}).
#pos(ex157@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 7). ghost(east, 6.0). food(east, 9). food(east, 8). wall(north). wall(east). wall(west). wall(south). ghost(east, 7.0). capsule(east, 5). capsule(east, 10). food(east, 10). ghost(west, 1.0).}).
#pos(ex158@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). wall(north). wall(east). ghost(east, 5.5). ghost(west, 1.0). wall(west). food(east, 10). wall(south). food(east, 6). capsule(east, 9). capsule(east, 4). food(east, 7).}).
#pos(ex159@3, {move(east)}, {move(south), move(north), move(west)}, {ghost(east, 5.0). food(east, 9). food(east, 8). wall(north). wall(east). ghost(west, 1.0). wall(west). food(east, 10). food(east, 5). wall(south). capsule(east, 8). food(east, 6). ghost(east, 4.0). capsule(east, 3). food(east, 7).}).
#pos(ex160@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). wall(north). ghost(east, 4.5). wall(east). ghost(east, 2.5). ghost(west, 1.0). capsule(south, 2). wall(west). food(east, 5). wall(south). food(east, 10). food(east, 4). capsule(east, 7). food(east, 6). food(east, 7).}).
#pos(ex161@3, {move(east)}, {move(south), move(north), move(west)}, {food(east, 9). food(east, 8). wall(north). food(east, 3). capsule(west, 3). wall(east). ghost(west, 1.0). wall(west). food(east, 5). wall(south). ghost(east, 1.0). ghost(south, 4.0). capsule(east, 6). food(east, 6). food(east, 4). food(east, 7).}).
#pos(ex162@5, {move(east)}, {move(south), move(north), move(west)}, {food(east, 8). wall(north). food(east, 3). wall(east). food(east, 2). ghost(west, 1.0). wall(west). food(east, 5). wall(south). capsule(east, 5). food(east, 6). ghost(west, 4.5). capsule(west, 4). food(east, 4). food(east, 7).}).
#pos(ex163@5, {move(east)}, {move(south), move(north), move(west)}, {capsule(west, 5). wall(north). food(east, 3). wall(east). food(east, 2). food(east, 1). ghost(west, 1.0). food(east, 5). wall(west). wall(south). capsule(east, 4). food(east, 6). ghost(west, 5.0). food(east, 4). food(east, 7).}).
#pos(ex164@5, {move(east)}, {move(south), move(north), move(west)}, {food(south, 3). food(east, 3). wall(north). wall(east). capsule(east, 3). food(south, 2). ghost(west, 5.5). food(east, 2). ghost(west, 1.0). wall(west). food(east, 5). food(south, 1). wall(south). food(east, 6). capsule(west, 6). food(south, 4). food(east, 1). food(east, 4).}).
#pos(ex165@5, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). food(south, 3). food(east, 3). ghost(west, 6). food(west, 3). wall(east). wall(north). food(east, 2). ghost(west, 1.0). capsule(south, 2). food(east, 5). food(west, 2). wall(west). wall(south). food(west, 5). capsule(west, 7). food(south, 4). food(east, 1). food(east, 4).}).
#pos(ex166@5, {move(east)}, {move(south), move(north), move(west)}, {food(west, 4). wall(north). food(east, 3). capsule(west, 3). food(west, 3). capsule(west, 8). wall(east). food(east, 2). ghost(west, 1.0). ghost(west, 6.0). wall(west). wall(south). food(west, 5). food(west, 6). food(east, 1). food(east, 4).}).
#pos(ex167@5, {move(south)}, {move(north), move(east), move(west)}, {food(west, 4). food(south, 3). wall(north). capsule(west, 9). wall(east). food(south, 2). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). food(west, 7). capsule(west, 4). food(west, 6). ghost(west, 1.0).}).
#pos(ex168@5, {move(north)}, {move(south), move(east), move(west)}, {food(west, 4). wall(north). capsule(west, 3). food(west, 3). capsule(west, 8). food(south, 2). wall(east). ghost(north, 1.0). ghost(west, 6.0). wall(west). wall(south). food(south, 1). food(west, 5). food(west, 6).}).
ranges_dist(0..10).
dir(north).
dir(south).
dir(east).
dir(west).


dist_thr(0).
dist_thr(1).
dist_thr(2).
dist_thr(4).


food_dist_geq(D, D1, D2) :- food(D, D1), dist_thr(D2), D1 >= D2.
food_dist_leq(D, D1, D2) :- food(D, D1), dist_thr(D2), D1 <= D2.
ghost_dist_geq(D, D1, D2) :- ghost(D, D1), dist_thr(D2), D1 >= D2.
ghost_dist_leq(D, D1, D2) :- ghost(D, D1), dist_thr(D2), D1 <= D2.
caps_dist_geq(D, D1, D2) :- capsule(D, D1), dist_thr(D2), D1 >= D2.
caps_dist_leq(D, D1, D2) :- capsule(D, D1), dist_thr(D2), D1 <= D2.

#modeb(1,food_dist_geq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,food_dist_leq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,ghost_dist_geq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,ghost_dist_leq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,caps_dist_geq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(1,caps_dist_leq(var(dir), var(ranges_dist), const(dist_thr))).
#modeb(not wall(var(dir))).

#modeh(move(var(dir))).

#maxv(3).

%bias declarations to ensure direction variables are the same
#bias(":- in_head(move(V0)), in_body(wall(X)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(food_dist_geq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(food_dist_leq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(ghost_dist_leq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(ghost_dist_geq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(caps_dist_leq(X,_,_)), V0!=X.").
#bias(":- in_head(move(V0)), in_body(caps_dist_geq(X,_,_)), V0!=X.").

%bias declarations to add rule penalties (bias search towards more general rules)
#bias("penalty(2, head(X)) :- in_head(X).").
#bias("penalty(1, body(X)) :- in_body(X).").